# Generated by Django 4.0.3 on 2022-04-02 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Título')),
                ('dir', models.CharField(max_length=30, verbose_name='Director')),
                ('act', models.CharField(max_length=30, verbose_name='ActorPrincipal')),
                ('date', models.DateField(verbose_name='FechaLanzamiento')),
            ],
        ),
    ]
