# Generated by Django 4.0.3 on 2022-04-03 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cineproyecto', '0002_cinemas_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='mail',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
    ]
