# Generated by Django 4.0.3 on 2022-04-13 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cineproyecto', '0003_alter_users_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinemas',
            name='mail',
            field=models.EmailField(max_length=254, verbose_name='Mail'),
        ),
        migrations.AlterField(
            model_name='users',
            name='birth_date',
            field=models.DateField(verbose_name='Fecha_de_Nacimiento'),
        ),
        migrations.AlterField(
            model_name='users',
            name='other_info',
            field=models.CharField(max_length=30, verbose_name='Otros_datos'),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_name',
            field=models.CharField(max_length=30, unique=True, verbose_name='Nombre_de_usuario'),
        ),
    ]
