# Generated by Django 4.0.3 on 2022-04-18 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cineproyecto', '0006_directors_movies_director'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='actor',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='director',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='act',
        ),
        migrations.AddField(
            model_name='movies',
            name='act',
            field=models.ManyToManyField(to='cineproyecto.actors'),
        ),
        migrations.RemoveField(
            model_name='movies',
            name='dir',
        ),
        migrations.AddField(
            model_name='movies',
            name='dir',
            field=models.ManyToManyField(to='cineproyecto.directors'),
        ),
    ]
