# Generated by Django 4.0.3 on 2022-04-18 23:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cineproyecto', '0007_delete_users_remove_movies_actor_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movies',
            options={'verbose_name': 'Película', 'verbose_name_plural': 'Películas'},
        ),
        migrations.AlterUniqueTogether(
            name='movies',
            unique_together={('name', 'date')},
        ),
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Título')),
                ('subtitle', models.CharField(max_length=60, verbose_name='Subtítulo')),
                ('body', models.CharField(max_length=300, verbose_name='Subtítulo')),
                ('date', models.DateField(verbose_name='FechaLanzamiento')),
                ('aprove', models.BooleanField(default='False')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entrada',
                'verbose_name_plural': 'Blogs',
            },
        ),
    ]
