# Generated by Django 4.0.3 on 2022-04-21 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cineproyecto', '0009_alter_blogs_body'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actors',
            options={'verbose_name': 'Actor', 'verbose_name_plural': 'Actores'},
        ),
        migrations.AlterModelOptions(
            name='cinemas',
            options={'verbose_name': 'Sala', 'verbose_name_plural': 'Cines'},
        ),
        migrations.AlterModelOptions(
            name='directors',
            options={'verbose_name': 'Director', 'verbose_name_plural': 'Directores'},
        ),
        migrations.AlterField(
            model_name='blogs',
            name='date',
            field=models.DateField(verbose_name='Creación'),
        ),
    ]
