# Generated by Django 4.0.3 on 2022-04-22 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cineproyecto', '0010_alter_actors_options_alter_cinemas_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actors',
            options={'ordering': ['surname'], 'verbose_name': 'Actor', 'verbose_name_plural': 'Actores'},
        ),
        migrations.AlterModelOptions(
            name='blogs',
            options={'ordering': ['date'], 'verbose_name': 'Entrada', 'verbose_name_plural': 'Blogs'},
        ),
        migrations.AlterModelOptions(
            name='cinemas',
            options={'ordering': ['name'], 'verbose_name': 'Sala', 'verbose_name_plural': 'Cines'},
        ),
        migrations.AlterModelOptions(
            name='directors',
            options={'ordering': ['surname'], 'verbose_name': 'Director', 'verbose_name_plural': 'Directores'},
        ),
        migrations.AlterModelOptions(
            name='movies',
            options={'ordering': ['name'], 'verbose_name': 'Película', 'verbose_name_plural': 'Películas'},
        ),
    ]
