# Generated by Django 4.0.3 on 2022-04-23 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cineproyecto', '0011_alter_actors_options_alter_blogs_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogs',
            options={'ordering': ['-date'], 'verbose_name': 'Entrada', 'verbose_name_plural': 'Blogs'},
        ),
        migrations.AlterField(
            model_name='movies',
            name='act',
            field=models.ManyToManyField(related_name='Actores', to='cineproyecto.actors'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='date',
            field=models.DateField(verbose_name='Fecha de Lanzamiento'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='dir',
            field=models.ManyToManyField(related_name='Director', to='cineproyecto.directors'),
        ),
    ]
