# Generated by Django 4.0.3 on 2022-04-23 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cineproyecto', '0012_alter_blogs_options_alter_movies_act_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='link',
            field=models.URLField(blank=True, db_index=True, max_length=128, unique=True, verbose_name='Trailer'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='act',
            field=models.ManyToManyField(to='cineproyecto.actors', verbose_name='Actores'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='dir',
            field=models.ManyToManyField(to='cineproyecto.directors', verbose_name='Director'),
        ),
    ]
