# Generated by Django 4.0.3 on 2022-04-23 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cineproyecto', '0013_movies_link_alter_movies_act_alter_movies_dir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='link',
            field=models.URLField(blank=True, verbose_name='Trailer'),
        ),
    ]
