# Generated by Django 4.0.3 on 2022-04-23 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cineproyecto', '0014_alter_movies_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='link',
        ),
    ]
