# Generated by Django 4.0.3 on 2022-04-23 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cineproyecto', '0015_remove_movies_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='link',
            field=models.URLField(blank=True, verbose_name='Trailer'),
        ),
    ]
