# Generated by Django 4.0.3 on 2022-04-24 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cineproyecto', '0016_movies_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='img',
            field=models.ImageField(blank=True, upload_to=None, verbose_name='Imagen'),
        ),
    ]
